name: modoStick
version: '${project.version}'
main: fr.yohem.modostick.ModoStick
api-version: 1.20
commands:
  stick:
    description: permet de voir le pseudo du joueur cibler
    usage: error
    permission: stick.give
    aliases:
      - stk
permissions:
  stick.give:
    description: se donner un baton de modo
    default: op
  stick.use:
    description: utiliser un baton de modo
    default: op